apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    -- Your SQL commands go here
    CREATE DATABASE "file-service";
    CREATE DATABASE "payment-service";
    CREATE DATABASE "lease-service"
    -- Others
