apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: postgres-dhrms
  name: postgres-dhrms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-dhrms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/microservices-project-microservices-network: "true"
        io.kompose.service: postgres-dhrms
    spec:
      containers:
        - name: postgres-dhrms
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: lisi
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: init-db-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-db-script
          configMap:
            name: postgres-init