apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: lease-service
  name: lease-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lease-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/microservices-project-microservices-network: "true"
        io.kompose.service: lease-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-dhrms.default.svc.cluster.local:5432/lease-service
          image: lisicao/lease-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          name: lease-service
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lease-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: lease-service
status:
  loadBalancer: {}
