apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8080
  selector:
    io.kompose.service: api-gateway
  type: LoadBalancer