apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: postgres-dhrms
  name: postgres-dhrms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-dhrms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/microservices-project-microservices-network: "true"
        io.kompose.service: postgres-dhrms
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: dhrms-service
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: lisi
          image: postgres
          name: postgres-dhrms
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-dhrms-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-dhrms-claim0
          persistentVolumeClaim:
            claimName: postgres-dhrms-claim0
