apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: postgres-order
  name: postgres-order
spec:
  ports:
    - name: "5431"
      port: 5431
      targetPort: 5431
    - name: 5431-tcp
      port: 5431
      targetPort: 5431
  selector:
    io.kompose.service: postgres-order
