apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/microservices-project-microservices-network: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:4.4.14-rc0-focal
          name: mongo
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1Gi"
              memory: "2Gi"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-claim0
      restartPolicy: Always
      volumes:
        - name: mongo-claim0
          persistentVolumeClaim:
            claimName: mongo-claim0
